FROM alpine
LABEL maintainer="mintflavor"
COPY ./ /api/
WORKDIR /api/
RUN apk update && \
    apk add --no-cache python3 py3-pip py3-requests && \
    pip3 install --no-cache-dir -r requirements.txt

EXPOSE 34567

CMD ["python3", "-m", "uvicorn", "main:app", "--host", "api", "--port", "34567"]